# Workflow derived from https://github.com/rstudio/r-manuals/blob/main/.github/workflows/build-website.yaml
on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

name: Build Site

jobs:
  build-website:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: quarto-dev/quarto-actions/setup@v2

      - name: Install pandoc
        run: |
          DEB=pandoc-2.19.2-1-amd64.deb
          wget https://github.com/jgm/pandoc/releases/download/2.19.2/$DEB
          sudo dpkg -i $DEB
          pandoc --version
        shell: bash

      - name: Install system requirements
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-ipafont
          sudo apt-get install -y libcurl4-openssl-dev
          fc-cache -fv

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-renv@v2

      - name: Build site 🔧
        run: Rscript scripts/build_website.R

      - name: Deploy 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: _site # The folder the action should deploy.
